[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "adk"
version = "1.0.0"
description = "Mock Agent Development Kit (ADK) for testing"
authors = [{name = "Mock Author"}]
readme = "README.md"
