version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/" # Looks for package.json in the root directory
    schedule:
      interval: "weekly"

  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/" # Looks for requirements.txt or pyproject.toml in the root directory
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    # Also update requirements.lock
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/" # Looks for Dockerfile in the root directory
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Looks for workflow files in .github/workflows
    schedule:
      interval: "weekly"
