# Optimized Gitleaks configuration with improved test handling

[allowlist]
description = "Allowlisted patterns and files"

paths = [
    "test_.*\\.py$",
    "tests/.*\\.py$",
    "conftest\\.py$",
    ".mypy_cache/.*",
    ".ruff_cache/.*",
    ".venv/.*",
    ".*\\.pyc$",
    "__pycache__/.*",
    "docs/.*\\.md$",
    "example_.*\\.json$",
    "node_modules/.*"
]

regexes = [
    "(TEST_PASSWORD|MOCK_PASSWORD|DUMMY_PASSWORD|SAMPLE_PASSWORD)[\"'][^\"']+[\"']",
    "(?i)password[\"'](test|mock|dummy|example|sample)[^\"']+[\"']",
    "0123456789ABCDEFabcdef",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567",
    "whsec_[a-zA-Z0-9]{24}",
    "[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}",
    "[0-9a-z]{32}",
    "binarySearch\\.GREATEST_LOWER_BOUND",
    "SourceMapConsumer\\.(GREATEST_LOWER_BOUND|LEAST_UPPER_BOUND)"
]

[[rules]]
id = "password-in-code"
description = "Password in code"
regex = '''(?i)(password|passwd|pwd)\s*[=:]\s*["'][^"']{8,}["']'''
keywords = [
    "password",
    "passwd",
    "pwd",
    "secret"
]
entropy = 3.5
exclude = [
    "(?i)test_password",
    "(?i)mock_password",
    "(?i)dummy_password",
    "(?i)example_password"
]

[[rules]]    
id = "high-entropy-string"
description = "High entropy string"
regex = '''["'][A-Za-z0-9\-._!@#$%^&*()]{16,}["']'''
entropy = 4.5
exclude = [
    "(?i)test[_-]",
    "(?i)mock[_-]",
    "(?i)dummy[_-]",
    "(?i)example[_-]",
    "(?i)greatest_lower_bound",
    "(?i)least_upper_bound"
]

[[rules]]
id = "environment-variable"
description = "Environment variable containing sensitive data"
regex = '''(?i)(api[_-]key|auth[_-]token|access[_-]key|secret[_-]key)\s*[=:]\s*["'][^"']+["']'''
entropy = 3.0
exclude = [
    "(?i)test[_-]",
    "(?i)mock[_-]",
    "(?i)dummy[_-]"
]
