# Define default exclude patterns for all hooks
# Using both absolute path pattern and directory name pattern to ensure .venv is fully excluded
exclude: |
  (?x)^(
    \.venv/|
    venv/|
    \.git/|
    .*\.venv/.*|
    .*venv/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast  # Check Python syntax
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Optional: Add mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive", "--explicit-package-bases", "--exclude=ai_models/cli/commands/__init__.py"]
        exclude: "^tests/"  # Exclude tests directory

  # Custom hooks to run our scripts
  - repo: local
    hooks:
      - id: check-syntax-errors
        name: Check for syntax errors
        entry: python fix_test_collection_warnings.py
        language: python
        types: [python]
        pass_filenames: false

      - id: format-files
        name: Format Python files
        entry: python format_files.py
        language: python
        types: [python]
        pass_filenames: true
