# Define default exclude patterns for all hooks
# Using regex pattern to exclude common third-party directories
exclude: |
  (?x)^(
    \.venv/|
    venv/|
    \.git/|
    node_modules/|
    .*\.venv/.*|
    .*venv/.*|
    .*node_modules/.*|
    .*__pycache__/.*|
    .*\.pytest_cache/.*|
    .*\.mypy_cache/.*|
    .*\.ruff_cache/.*|
    .*build/.*|
    .*dist/.*
  )$

# Add fail_fast: false to continue running hooks even if one fails
fail_fast: false

# Add auto-stage-modified: true to automatically stage files that are modified by hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast  # Check Python syntax
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [
          "--check",
          "--format=github",
          "--select=E,F,W,I,N,B,UP,ANN,S,BLE,FBT,C,DTZ,T20,RET,SIM,PL,RUF",
          "--ignore=ANN101,ANN102,ANN204"
        ]
      - id: ruff-format
        args: ["--check"]

  # Optional: Add mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive", "--explicit-package-bases", "--exclude=ai_models/cli/commands/__init__.py"]
        exclude: "^tests/"  # Exclude tests directory  # Add gitleaks for local secret scanning
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        name: gitleaks detect secrets
        entry: gitleaks detect --no-git -v --config=.gitleaks.toml --no-banner
        language: golang
        types: [file]
        pass_filenames: false
        require_serial: true
        additional_dependencies: []
        always_run: true
        verbose: true
        # Override the global exclude pattern with a more specific one for gitleaks
        exclude: |
          (?x)^(
            \.venv/.*|
            venv/.*|
            node_modules/.*|
            \.git/.*|
            __pycache__/.*|
            \.pytest_cache/.*|
            \.mypy_cache/.*|
            \.ruff_cache/.*|
            build/.*|
            dist/.*|
            .*\.min\.(js|css)$|
            .*\.(jpg|jpeg|png|gif|bmp|svg|mp4|avi|mov|wmv|mp3|wav|ogg|pdf|doc|docx|xls|xlsx|ppt|pptx|zip|tar|gz|rar)$|
            \.github/workflows/.*\.yml$
          )
