# Pre-commit configuration optimized for speed and parallel execution
default_language_version:
    python: python3

# Optimized exclude patterns
exclude:
  (?x)(
    ^\.venv/.*|
    ^venv/.*|
    ^env/.*|
    \.venv/.*|
    venv/.*|
    env/.*|
    \.git/.*|
    node_modules/.*|
    .*__pycache__/.*|
    .*\.pytest_cache/.*|
    .*\.mypy_cache/.*|
    .*\.ruff_cache/.*|
    build/.*|
    dist/.*|
    .*\.egg-info/.*|
    ui/react_frontend/node_modules/.*|
    sdk/javascript/node_modules/.*
  )

default_stages: [pre-commit]
fail_fast: false

repos:
  # Fast validation hooks (run first)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']

  # Security checks (run early to fail fast)
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.25.1
    hooks:
      - id: gitleaks
        name: Detect secrets with Gitleaks
        entry: gitleaks protect --staged -v --config=.gitleaks.toml --no-banner
        language: golang
        pass_filenames: false
        stages: [pre-commit, pre-merge-commit]

  # Primary code quality tool: Ruff (formatting, linting, import sorting)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff-format
        name: Format code with Ruff
        types: [python]
        files: \.py$
      - id: ruff
        name: Lint with Ruff
        args: [--fix, --exit-non-zero-on-fix]
        types: [python]
        files: \.py$

  # Type checking (run after formatting/linting)
  - repo: local
    hooks:
      - id: mypy
        name: Type check with MyPy
        entry: python -m mypy
        language: system
        types: [python]
        require_serial: true
        exclude: |
          (?x)(
            ^scripts/__init__.py$|
            ^.github/scripts/__init__.py$
          )
        args: [
          "--install-types",
          "--non-interactive",
          "--disable-error-code=attr-defined",
          "--disable-error-code=name-defined",
          "--disable-error-code=unused-ignore",
          "--namespace-packages",
          "--explicit-package-bases"
        ]

  # Optimized local hooks for incremental checks
  - repo: local
    hooks:
      - id: incremental-quality
        name: Run incremental quality checks
        entry: python scripts/manage_quality.py incremental
        language: system
        types: [python]
        pass_filenames: true
        stages: [pre-commit]
        exclude: |
          (?x)(
            ^scripts/__init__.py$|
            ^.github/scripts/__init__.py$
          )
