# Define default exclude patterns for all hooks
# Using both absolute path pattern and directory name pattern to ensure .venv is fully excluded
exclude: |
  (?x)^(
    \.venv/|
    venv/|
    \.git/|
    .*\.venv/.*|
    .*venv/.*
  )$

# Add fail_fast: false to continue running hooks even if one fails
fail_fast: false

# Add auto-stage-modified: true to automatically stage files that are modified by hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast  # Check Python syntax
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Optional: Add mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive", "--explicit-package-bases", "--exclude=ai_models/cli/commands/__init__.py"]
        exclude: "^tests/"  # Exclude tests directory

  # Unified local quality and security check
  - repo: local
    hooks:
      - id: manage-quality
        name: Unified Quality/Security/Formatting (manage_quality.py)
        entry: python scripts/manage_quality.py pre-commit
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        description: "Run all code quality, formatting, lint, syntax, docstring, and security checks via the unified script."

  # Unified local code quality hooks (entrypoint: scripts/manage_quality.py)
  - repo: local
    hooks:
      - id: unified-lint
        name: Unified Lint
        entry: python scripts/manage_quality.py lint
        language: system
        types: [python]
      - id: unified-format
        name: Unified Format
        entry: python scripts/manage_quality.py format
        language: system
        types: [python]
      - id: unified-fix
        name: Unified Fix
        entry: python scripts/manage_quality.py fix
        language: system
        types: [python]
      - id: unified-docstring-fix
        name: Unified Docstring Fix
        entry: python scripts/manage_quality.py docstring-fix
        language: system
        types: [python]
      - id: unified-syntax-fix
        name: Unified Syntax Fix
        entry: python scripts/manage_quality.py syntax-fix
        language: system
        types: [python]
      - id: unified-security-scan
        name: Unified Security Scan
        entry: python scripts/manage_quality.py security-scan
        language: system
        types: [python]
