# Define default exclude patterns for all hooks
# Using regex pattern to exclude common third-party directories
exclude: |
  (?x)^(
    \.venv/|
    venv/|
    \.git/|
    node_modules/|
    .*\.venv/.*|
    .*venv/.*|
    .*node_modules/.*|
    .*__pycache__/.*|
    .*\.pytest_cache/.*|
    .*\.mypy_cache/.*|
    .*\.ruff_cache/.*|
    .*build/.*|
    .*dist/.*
  )$

# Add fail_fast: false to continue running hooks even if one fails
fail_fast: false

# Add auto-stage-modified: true to automatically stage files that are modified by hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: ".*package-lock\\.json$"
      - id: check-ast  # Check Python syntax
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        types: [python]
        files: \.py$
        entry: ruff check
      - id: ruff-format
        types: [python]
        files: \.py$
        entry: ruff format

  # Optional: Add mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive", "--explicit-package-bases", "--exclude=ai_models/cli/commands/__init__.py"]
        exclude: "^tests/"  # Exclude tests directory
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        name: gitleaks detect secrets
        entry: gitleaks detect --no-git -v --config=.gitleaks.toml --no-banner
        language: golang
        types: [file]
        pass_filenames: false
        require_serial: true
        additional_dependencies: []
        always_run: true
        verbose: true
        # Override the global exclude pattern with a more specific one for gitleaks
        exclude: |
          (?x)^(
            \.venv/.*|
            venv/.*|
            node_modules/.*|
            \.git/.*|
            __pycache__/.*|
            \.pytest_cache/.*|
            \.mypy_cache/.*|
            \.ruff_cache/.*|
            build/.*|
            dist/.*|
            .*\.min\.(js|css)$|
            .*\.(jpg|jpeg|png|gif|bmp|svg|mp4|avi|mov|wmv|mp3|wav|ogg|pdf|doc|docx|xls|xlsx|ppt|pptx|zip|tar|gz|rar)$|
            \.github/workflows/.*\.yml$|
            .*playwright-report/.*|
            .*ui/react_frontend/playwright-report/.*
          )

  # Unified local code quality workflow
  -   repo: local
      hooks:
        - id: unified-lint
          name: Unified Lint
          entry: python scripts/manage_quality.py lint
          language: system
          types: [python]
        - id: unified-format
          name: Unified Format
          entry: python scripts/manage_quality.py format
          language: system
          types: [python]
        - id: unified-fix
          name: Unified Fix
          entry: python scripts/manage_quality.py fix
          language: system
          types: [python]
        - id: unified-docstring-fix
          name: Unified Docstring Fix
          entry: python scripts/manage_quality.py docstring-fix
          language: system
          types: [python]
        - id: unified-syntax-fix
          name: Unified Syntax Fix
          entry: python scripts/manage_quality.py syntax-fix
          language: system
          types: [python]
        - id: unified-security
          name: Unified Security Scan
          entry: python scripts/manage_quality.py security-scan
          language: system
          types: [python]
        - id: unified-test
          name: Unified Test
          entry: python scripts/manage_quality.py test
          language: system
          types: [python]

  # Unified local hooks for code quality and security
  - repo: local
    hooks:
      - id: manage-quality-fix
        name: Run all code fixers (unified)
        entry: python scripts/manage_quality.py fix
        language: system
        types: [python]
      - id: manage-quality-docstring
        name: Fix docstring issues (unified)
        entry: python scripts/manage_quality.py docstring-fix
        language: system
        types: [python]
      - id: manage-quality-syntax
        name: Fix syntax issues (unified)
        entry: python scripts/manage_quality.py syntax-fix
        language: system
        types: [python]
      - id: manage-quality-security
        name: Run security scans (unified)
        entry: python scripts/manage_quality.py security-scan
        language: system
        types: [python]
      - id: manage-quality-test
        name: Run all tests (unified)
        entry: python scripts/manage_quality.py test
        language: system
        types: [python]
      - id: manage-quality-pre-commit
        name: Run pre-commit checks (unified)
        entry: python scripts/manage_quality.py pre-commit
        language: system
        types: [python]
