version: '3.8'

# This override file is specifically for CI environments
services:
  app:
    # Add CI-specific environment variables
    environment:
      - FLASK_ENV=testing 
      - TESTING=true
      - LOG_LEVEL=DEBUG
      - CI=true
      - CONTAINER=true
      - HEALTHCHECK_MAX_RETRIES=10
      - HEALTHCHECK_INITIAL_RETRY_INTERVAL=2
      - HEALTHCHECK_CURL_TIMEOUT=5
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key_for_ci}  # Required for mem0
      - GITHUB_ACTIONS=true
    healthcheck:
      test: ["CMD", "/app/docker-healthcheck.sh"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  frontend:
    build:
      context: ./ui/react_frontend
      dockerfile: Dockerfile.dev
      args:
        - CI=true
    environment:
      - NODE_ENV=test
      - CI=true
      - SKIP_PREFLIGHT_CHECK=true
      - REACT_APP_TESTING=true
      - GITHUB_ACTIONS=true
