version: '3.8'

# This override file is specifically for CI environments
services:
  app:
    # Reduce resource requirements for CI
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 512M
    # Adjust healthcheck for CI - faster checks with more retries
    healthcheck:
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    # Add CI-specific environment variables
    environment:
      - FLASK_ENV=testing
      - TESTING=true
      - LOG_LEVEL=DEBUG
      - CI=true
      - CONTAINER=true
      - HEALTHCHECK_MAX_RETRIES=10
      - HEALTHCHECK_INITIAL_RETRY_INTERVAL=2
      - HEALTHCHECK_CURL_TIMEOUT=5
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key_for_ci}  # Required for mem0

  frontend:
    # Use a simpler build for CI
    build:
      context: ./ui/react_frontend
      dockerfile: Dockerfile.dev
      args:
        - CI=true
    # Adjust healthcheck for CI
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Add CI-specific environment variables
    environment:
      - NODE_ENV=test
      - CI=true
      - SKIP_PREFLIGHT_CHECK=true
      - REACT_APP_TESTING=true
      - NPM_CONFIG_LEGACY_PEER_DEPS=true
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
      - REACT_APP_AG_UI_ENABLED=true

  db:
    # Use a smaller configuration for CI
    command: [
      "postgres",
      "-c", "max_connections=50",
      "-c", "shared_buffers=128MB",
      "-c", "fsync=off",
      "-c", "synchronous_commit=off",
      "-c", "full_page_writes=off"
    ]
    # Adjust healthcheck for CI - faster checks with more retries
    healthcheck:
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 10s
    # Reduce memory usage for CI
    shm_size: 128mb
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
