[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "paissive_income"
version = "0.1.0"
description = "pAIssive Income project - AI-powered passive income generation platform"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "pAIssive Income Team"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi>=0.95.0",
    "uvicorn>=0.22.0",
    "pydantic>=2.0.0",
    "python-consul>=1.1.0",
    "python-jose[cryptography]>=3.3.0",
    "redis>=4.5.0",
    "flask>=2.0.1",
    "httpx>=0.24.0",
    "crewai>=0.120.0",  # AI agent orchestration framework
    # Add other dependencies as needed
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.10.0",
    "pytest-asyncio>=0.21.0",
]
ml = [
    "torch>=1.10.0",
    "transformers>=4.20.0",
    "sentence-transformers>=2.2.0",
    "numpy>=1.24.3",
    "scikit-learn>=1.0.0",
]

[project.urls]
homepage = "https://github.com/yourusername/pAIssive_income"
bug_tracker = "https://github.com/yourusername/pAIssive_income/issues"

[tool.setuptools]
packages = ["services"]
package-dir = {"" = "."}
package-data = {"services" = ["**/*.json"]}

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.mypy]
python_version = "3.10"
exclude = ["ui/react_frontend", "scripts/__init__.py", ".github/scripts/__init__.py", ".github/scripts"]
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = false
ignore_missing_imports = true
warn_return_any = false
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = false
warn_no_return = false
warn_unreachable = false
show_error_codes = true
cache_dir = ".mypy_cache"
incremental = true
follow_imports = "skip"
follow_imports_for_stubs = true
namespace_packages = true
explicit_package_bases = true
mypy_path = "mypy_stubs"
files = ["!scripts/__init__.py", "!.github/scripts/__init__.py"]

[[tool.mypy.overrides]]
module = "mypy.plugins.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "run_ui"
ignore_errors = true

[[tool.mypy.overrides]]
module = "migrations.env"
ignore_errors = true

[[tool.mypy.overrides]]
module = "users.password_reset"
ignore_errors = true

[[tool.mypy.overrides]]
module = "api.utils.auth"
ignore_errors = true

[[tool.mypy.overrides]]
module = "test_sarif_utils"
ignore_errors = true

[[tool.mypy.overrides]]
module = "run_mcp_tests"
ignore_errors = true

[[tool.mypy.overrides]]
module = "install_mcp_sdk"
ignore_errors = true

[[tool.mypy.overrides]]
module = "scripts.manage_quality"
ignore_errors = true

[[tool.mypy.overrides]]
module = "tests.api.*"
ignore_errors = true
