# Line length configuration
line-length = 88

# Enable auto-fixes
fix = true

# Exclude non-Python files
exclude = [
    ".git",
    ".github/workflows/*.yml",
    "*.md",
    "Dockerfile",
    ".dockerignore",
    "docker-compose.yml",
    "*.json",
    "*.yaml",
    "*.yml",
    "*.toml",
    "*.ini",
    "*.cfg",
    "*.txt",
    "!src/**/*.py",
    "!tests/**/*.py",
    "!utils/**/*.py"
]

[lint]
# Enable pycodestyle (`E`), Pyflakes (`F`), and more
select = ["E", "F", "W", "I", "N", "D", "UP", "B"]
ignore = [
    "D203",  # Ignore 'incorrect-blank-line-before-class' in favor of D211
    "D213",  # Ignore 'multi-line-summary-second-line' in favor of D212
]

# Enable isort rules
extend-select = ["I"]

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"comprehensive_fix_linting.py" = ["E501"]
"fix_all_issues_final.py" = ["E501"]
"ai_models/adapters/openai_compatible_adapter.py" = ["E501"]
"ai_models/examples/agent_integration_example.py" = ["E501"]
"ai_models/examples/performance_monitor_example.py" = ["E501"]
"ai_models/optimization/quantization/bitsandbytes_quantizer.py" = ["E501"]
"ai_models/serving/rest_api/routes/text_classification.py" = ["E501"]
"sdk/python/paissive_income_sdk/services/niche_analysis.py" = ["E501"]
"services/service_discovery/consul_service_registry.py" = ["E501"]
"tests/ai_models/fallbacks/test_fallback_standalone.py" = ["E501"]
"tests/ai_models/fallbacks/test_fallback_strategy.py" = ["E501"]
"tests/ai_models/test_model_version_compatibility.py" = ["E501"]
"tests/api/test_webhook_delivery_integration.py" = ["E501"]
"tests/api/test_webhook_delivery_reliability.py" = ["E501"]
"tests/api/test_webhook_event_processing.py" = ["E501"]
"tests/api/test_webhook_performance_recovery.py" = ["E501"]
"tests/api/test_webhook_schema_edge_cases.py" = ["E501"]
"tests/api/test_webhook_security_advanced.py" = ["E501"]
"tests/common_utils/db/test_concurrent_operations.py" = ["E501"]
"tests/common_utils/test_analysis_batch_utils.py" = ["E501"]
"tests/integration/test_ai_models_integration.py" = ["E501"]
"tests/integration/test_analytics_data_collection.py" = ["E501"]
"tests/integration/test_api_gateway_circuit_breaker.py" = ["E501"]
"tests/integration/test_competitor_to_pricing_workflow.py" = ["E501"]
"tests/integration/test_error_recovery_workflows.py" = ["E501"]
"tests/integration/test_message_queue_integration.py" = ["E501"]
"tests/integration/test_microservices_integration.py" = ["E501"]
"tests/integration/test_monetization_integration.py" = ["E501"]
"tests/integration/test_monetization_to_marketing.py" = ["E501"]
"tests/integration/test_niche_to_ab_testing_workflow.py" = ["E501"]
"tests/integration/test_persona_to_ab_testing_workflow.py" = ["E501"]
"tests/integration/test_service_dependency_resolution.py" = ["E501"]
"tests/integration/test_service_version_compatibility.py" = ["E501"]
"tests/integration/test_solution_to_monetization.py" = ["E501"]
"tests/integration/test_webhook_api_integration.py" = ["E501"]
"tests/integration/test_webhook_middleware_integration.py" = ["E501"]
"tests/integration/test_webhook_security_integration.py" = ["E501"]
"tests/performance/test_resource_utilization.py" = ["E501"]
"tests/security/test_advanced_authentication.py" = ["E501"]
"tests/security/test_authorization_edge_cases.py" = ["E501"]
"tests/test_fix_test_collection_warnings.py" = ["E501"]
"tests/test_run_github_actions_locally.py" = ["E501"]
"tests/unit/common_utils/caching/test_namespace_clearing.py" = ["E501"]

[lint.extend-per-file-ignores]
"*/__init__.py" = ["E402"]
"tests/**/*.py" = ["E501"]  # Ignore line length in all test files

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
