"""
Common utilities for the pAIssive Income project.

This package provides common utility functions used across the project,
including date handling, JSON serialization, and file operations.
"""

from .date_utils import (
    add_days,
    add_months,
    add_years,
    format_date,
    format_datetime,
    get_date_difference,
    get_days_in_month,
    get_days_in_year,
    get_end_of_day,
    get_end_of_month,
    get_end_of_week,
    get_end_of_year,
    get_start_of_day,
    get_start_of_month,
    get_start_of_week,
    get_start_of_year,
    is_date_in_range,
    is_future_date,
    is_past_date,
    is_same_day,
    is_same_month,
    is_same_year,
)
from .file_utils import (
    create_directory,
    file_exists,
    get_directory_path,
    get_file_extension,
    get_file_name,
    get_file_path,
    get_file_size,
    list_directories,
    list_files,
    read_file,
    write_file,
)
from .json_utils import (
    from_json,
    json_deserialize,
    json_serialize,
    load_from_json_file,
    save_to_json_file,
    to_json,
)
from .string_utils import (
    camel_to_snake,
    format_currency,
    format_number,
    format_percentage,
    is_blank,
    is_empty,
    slugify,
    snake_to_camel,
    truncate,
)

__all__ = [
    # Date utilities
    "format_date",
    "format_datetime",
    "get_days_in_month",
    "get_days_in_year",
    "get_start_of_day",
    "get_start_of_week",
    "get_start_of_month",
    "get_start_of_year",
    "get_end_of_day",
    "get_end_of_week",
    "get_end_of_month",
    "get_end_of_year",
    "is_date_in_range",
    "get_date_difference",
    "add_days",
    "add_months",
    "add_years",
    "is_future_date",
    "is_past_date",
    "is_same_day",
    "is_same_month",
    "is_same_year",
    # JSON utilities
    "to_json",
    "from_json",
    "save_to_json_file",
    "load_from_json_file",
    "json_serialize",
    "json_deserialize",
    # File utilities
    "read_file",
    "write_file",
    "file_exists",
    "create_directory",
    "get_file_path",
    "get_directory_path",
    "list_files",
    "list_directories",
    "get_file_extension",
    "get_file_name",
    "get_file_size",
    # String utilities
    "is_empty",
    "is_blank",
    "truncate",
    "slugify",
    "camel_to_snake",
    "snake_to_camel",
    "format_currency",
    "format_number",
    "format_percentage",
]
