apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paissive-income-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
