apiVersion: v1
kind: Service
metadata:
  name: paissive-income-service
  labels:
    app: paissive-income
spec:
  selector:
    app: paissive-income
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  type: LoadBalancer
