from typing import Any, Callable, Dict

# Define a Flask class
class Flask:
    def __init__(self, import_name: str, **kwargs: Any) -> None: ...
    def config(self) -> dict[str, Any]: ...
    def route(self, rule: str, **options: Any) -> Callable: ...
    def register_blueprint(self, blueprint: Any, **options: Any) -> None: ...
    def app_context(self) -> Any: ...
    def run(
        self, host: str = ..., port: int = ..., debug: bool = ..., **options: Any
    ) -> None: ...

# Define current_app
current_app: Flask
