name: Simple Lint Check for Act
on: [workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort ruff
      - name: Run linting checks
        run: |
          if [ -n "$FILE" ]; then
            echo "Linting specific file: $FILE"
            python run_linting.py "$FILE"
          else
            echo "Linting comprehensive_fix_linting.py"
            python run_linting.py comprehensive_fix_linting.py
          fi
