name: Auto-fix
on:
  pull_request:
    paths:
      - "**.py"
      - "**.js"
      - "**.ts"
      - "**.tsx"
      - "**.jsx"
      - "**.json"
      - "**.yml"
      - "**.yaml"

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix Python code
        run: |
          pip install ruff
          ruff --fix .

      - name: Fix JavaScript/TypeScript code
        run: |
          npm install -g prettier
          prettier --write .

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -am "Auto-fix: Apply ruff and prettier fixes"
          git push
