name: CI/CD Monitoring

on:
  workflow_run:
    workflows: ["CI/CD Pipeline", "Security Scan", "Deploy"]
    types:
      - completed

jobs:
  Monitor_Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow status
        id: check_status
        run: |
          echo "Workflow ${{ github.event.workflow_run.name }} completed with status: ${{ github.event.workflow_run.conclusion }}"
          echo "workflow_status=${{ github.event.workflow_run.conclusion }}" >> $GITHUB_OUTPUT
          echo "workflow_name=${{ github.event.workflow_run.name }}" >> $GITHUB_OUTPUT
          echo "workflow_url=${{ github.event.workflow_run.html_url }}" >> $GITHUB_OUTPUT
          echo "repo_name=${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "branch_name=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT

      - name: Send Slack notification on failure
        if: steps.check_status.outputs.workflow_status != 'success'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "⚠️ CI/CD Workflow Failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "⚠️ CI/CD Workflow Failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow:*\n${{ steps.check_status.outputs.workflow_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n${{ steps.check_status.outputs.workflow_status }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ steps.check_status.outputs.repo_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ steps.check_status.outputs.branch_name }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow",
                        "emoji": true
                      },
                      "url": "${{ steps.check_status.outputs.workflow_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send email notification on failure
        if: steps.check_status.outputs.workflow_status != 'success'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "⚠️ CI/CD Workflow Failed: ${{ steps.check_status.outputs.workflow_name }}"
          body: |
            CI/CD Workflow has failed!
            
            Workflow: ${{ steps.check_status.outputs.workflow_name }}
            Status: ${{ steps.check_status.outputs.workflow_status }}
            Repository: ${{ steps.check_status.outputs.repo_name }}
            Branch: ${{ steps.check_status.outputs.branch_name }}
            
            View the workflow run: ${{ steps.check_status.outputs.workflow_url }}
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: CI/CD Monitoring <${{ secrets.MAIL_USERNAME }}>

  Collect_Metrics:
    runs-on: ubuntu-latest
    needs: Monitor_Workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas matplotlib

      - name: Collect workflow metrics
        run: |
          python .github/scripts/collect_workflow_metrics.py \
            --workflow "${{ github.event.workflow_run.name }}" \
            --status "${{ github.event.workflow_run.conclusion }}" \
            --duration "${{ github.event.workflow_run.updated_at - github.event.workflow_run.created_at }}" \
            --branch "${{ github.event.workflow_run.head_branch }}" \
            --commit "${{ github.event.workflow_run.head_sha }}" \
            --output "workflow_metrics.json"

      - name: Upload metrics as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workflow-metrics
          path: workflow_metrics.json
          retention-days: 90
