name: CI/CD Monitoring

on:
  workflow_run:
    workflows: ["CI/CD Pipeline", "Security Scan", "Deploy"]
    types:
      - completed

jobs:
  Monitor_Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow status
        id: check_status
        env:
          # Store potentially dangerous input in environment variables first
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo "Workflow ${{ github.event.workflow_run.name }} completed with status: ${{ github.event.workflow_run.conclusion }}"
          echo "workflow_status=${{ github.event.workflow_run.conclusion }}" >> $GITHUB_OUTPUT
          echo "workflow_name=${{ github.event.workflow_run.name }}" >> $GITHUB_OUTPUT
          echo "workflow_url=${{ github.event.workflow_run.html_url }}" >> $GITHUB_OUTPUT
          echo "repo_name=${{ github.repository }}" >> $GITHUB_OUTPUT

          # Safely extract and validate branch name to prevent expression injection
          # Store raw branch name in a variable from environment variable and remove any special characters
          RAW_BRANCH=$(echo "$HEAD_BRANCH" | tr -d '\n' | tr -cd 'a-zA-Z0-9_\-\/')

          # Additional safety check - if empty after sanitization, use default
          if [ -z "$RAW_BRANCH" ]; then
            RAW_BRANCH="invalid-branch-name"
            echo "WARNING: Branch name was empty or contained only invalid characters. Using placeholder instead."
          fi

          # Escape any characters that could cause issues in GitHub expressions
          SAFE_BRANCH=$(echo "$RAW_BRANCH" | sed 's/[&]/\\&/g')

          # Store the sanitized branch name
          echo "branch_name=$SAFE_BRANCH" >> $GITHUB_OUTPUT

      - name: Send Slack notification on failure
        if: steps.check_status.outputs.workflow_status != 'success'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "⚠️ CI/CD Workflow Failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "⚠️ CI/CD Workflow Failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow:*\n${{ steps.check_status.outputs.workflow_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n${{ steps.check_status.outputs.workflow_status }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ steps.check_status.outputs.repo_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ steps.check_status.outputs.branch_name }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow",
                        "emoji": true
                      },
                      "url": "${{ steps.check_status.outputs.workflow_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send email notification on failure
        if: steps.check_status.outputs.workflow_status != 'success'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "⚠️ CI/CD Workflow Failed: ${{ steps.check_status.outputs.workflow_name }}"
          body: |
            CI/CD Workflow has failed!

            Workflow: ${{ steps.check_status.outputs.workflow_name }}
            Status: ${{ steps.check_status.outputs.workflow_status }}
            Repository: ${{ steps.check_status.outputs.repo_name }}
            Branch: ${{ steps.check_status.outputs.branch_name }}

            View the workflow run: ${{ steps.check_status.outputs.workflow_url }}
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: CI/CD Monitoring <${{ secrets.MAIL_USERNAME }}>

  Collect_Metrics:
    runs-on: ubuntu-latest
    needs: Monitor_Workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas matplotlib

      - name: Validate branch name and calculate duration
        id: validate_branch
        env:
          # Store potentially dangerous inputs in environment variables first
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          CREATED_AT_TIME: ${{ github.event.workflow_run.created_at }}
          UPDATED_AT_TIME: ${{ github.event.workflow_run.updated_at }}
        run: |
          # Safely extract and validate branch name - strictly sanitize by removing all characters except allowed ones
          RAW_BRANCH=$(echo "$HEAD_BRANCH" | tr -d '\n' | tr -cd 'a-zA-Z0-9_\-\/')

          # Additional safety check - if empty after sanitization, use default
          if [ -z "$RAW_BRANCH" ]; then
            RAW_BRANCH="invalid-branch-name"
            echo "WARNING: Branch name was empty or contained only invalid characters. Using placeholder instead."
          fi

          # Escape any characters that could cause issues in GitHub expressions
          SAFE_BRANCH=$(echo "$RAW_BRANCH" | sed 's/[&]/\\&/g')

          # Store the sanitized branch name
          echo "branch=$SAFE_BRANCH" >> $GITHUB_OUTPUT

          # Safely calculate duration in seconds
          # Extract timestamps and strictly sanitize to ensure they only contain valid ISO 8601 characters
          CREATED_AT=$(echo "$CREATED_AT_TIME" | tr -d '\n' | tr -cd '0-9T:-Z')
          UPDATED_AT=$(echo "$UPDATED_AT_TIME" | tr -d '\n' | tr -cd '0-9T:-Z')

          # Validate timestamps format (ISO 8601) with strict pattern matching
          if [[ "$CREATED_AT" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]] &&
             [[ "$UPDATED_AT" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]]; then
            # Calculate duration only if timestamps are valid, using a safer approach
            CREATED_SECONDS=$(date -d "$CREATED_AT" +%s || echo "0")
            UPDATED_SECONDS=$(date -d "$UPDATED_AT" +%s || echo "0")

            # Additional validation to ensure we got valid seconds
            if [[ "$CREATED_SECONDS" =~ ^[0-9]+$ ]] && [[ "$UPDATED_SECONDS" =~ ^[0-9]+$ ]]; then
              DURATION=$(( UPDATED_SECONDS - CREATED_SECONDS ))
              # Ensure duration is not negative
              if [ "$DURATION" -lt 0 ]; then
                DURATION=0
              fi
              echo "duration=$DURATION" >> $GITHUB_OUTPUT
            else
              echo "duration=0" >> $GITHUB_OUTPUT
              echo "WARNING: Invalid timestamp conversion. Using 0 for duration."
            fi
          else
            # Use a default duration if timestamps are invalid
            echo "duration=0" >> $GITHUB_OUTPUT
            echo "WARNING: Invalid timestamp format detected. Using 0 for duration."
          fi

      - name: Collect workflow metrics
        run: |
          python .github/scripts/collect_workflow_metrics.py \
            --workflow "${{ github.event.workflow_run.name }}" \
            --status "${{ github.event.workflow_run.conclusion }}" \
            --duration "${{ steps.validate_branch.outputs.duration }}" \
            --branch "${{ steps.validate_branch.outputs.branch }}" \
            --commit "${{ github.event.workflow_run.head_sha }}" \
            --output "workflow_metrics.json"

      - name: Upload metrics as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workflow-metrics
          path: workflow_metrics.json
          retention-days: 90
