name: Consolidated CI/CD

# Consolidated CI/CD Pipeline
# This workflow handles continuous integration and deployment across multiple platforms.
#
# Jobs:
# - lint-test: Code quality, type checking, and testing
#   - Runs on: Ubuntu, Windows, MacOS
#   - Performs: linting (ruff), type checking (mypy), testing (pytest)
#   - Generates: test reports and coverage data
#
# - security: Comprehensive security scanning
#   - Runs on: Ubuntu, Windows, MacOS
#   - Tools: Safety, Bandit, Trivy, Semgrep, pip-audit, Gitleaks
#   - Generates: SARIF reports and security artifacts
#
# - build-deploy: Docker image building and publishing
#   - Runs on: Ubuntu only (for Docker compatibility)
#   - Triggers: On main/dev branch pushes and version tags
#   - Handles: Docker image building, caching, and publishing
#   - Uses: Docker Buildx for optimized builds

on:
  push:
    branches: [ main, dev, master, develop ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main, dev, master, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly, for regular security scans
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-test:
    name: Lint, Type Check, and Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies (Unix)
        if: runner.os != 'Windows'
        run: |
          # Ensure pip is up to date
          python -m pip install --upgrade pip

          # Install uv if not already available
          which uv || python -m pip install uv

          # Install testing tools
          python -m pip install ruff mypy pytest pytest-cov pytest-xdist pytest-asyncio python-multipart

          # Install requirements-dev.txt first
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi

          # Install the package in development mode with dev extras only
          # Avoid installing the agents extra which has dependency conflicts
          python -m pip install -e ".[dev]"

          # Install MCP SDK using the installation script
          echo "Installing MCP SDK using installation script..."
          python install_mcp_sdk.py

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Ensure pip is up to date
          python -m pip install --upgrade pip

          # Install testing tools
          python -m pip install ruff mypy pytest pytest-cov pytest-xdist pytest-asyncio python-multipart

          # Install requirements-dev.txt first
          if (Test-Path requirements-dev.txt) {
            python -m pip install -r requirements-dev.txt
          }

          # Install the package in development mode with dev extras only
          # Avoid installing the agents extra which has dependency conflicts
          python -m pip install -e ".[dev]"

      - name: Run linting (Unix)
        if: runner.os != 'Windows'
        run: |
          # Run linting tools
          ruff check .
          mypy .

      - name: Run linting (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Skip MCP adapter files during linting on Windows
          ruff check --exclude "ai_models/adapters/mcp_adapter.py" --exclude "tests/ai_models/adapters/test_mcp_adapter.py" --exclude "tests/test_mcp_import.py" --exclude "tests/test_mcp_top_level_import.py" .
          mypy --exclude "ai_models/adapters/mcp_adapter.py" --exclude "tests/ai_models/adapters/test_mcp_adapter.py" --exclude "tests/test_mcp_import.py" --exclude "tests/test_mcp_top_level_import.py" .

      - name: Run MCP tests (Unix only)
        if: runner.os != 'Windows'
        run: |
          # Run MCP adapter tests separately using the custom script
          python run_mcp_tests.py

      - name: Run other tests
        run: |
          # Run all tests except MCP adapter tests
          pytest -v --cov=. --cov-report=xml --cov-report=term-missing --cov-fail-under=80 --ignore=tests/ai_models/adapters/test_mcp_adapter.py --ignore=tests/test_mcp_import.py --ignore=tests/test_mcp_top_level_import.py

      - name: Setup Node.js for frontend tests
        if: runner.os == 'Windows'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm for frontend tests
        if: runner.os == 'Windows'
        uses: pnpm/action-setup@v4
        with:
          version: '8'

      - name: Run frontend tests (Windows only)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Check if the React frontend directory exists
          if (Test-Path ui/react_frontend) {
            Write-Host "React frontend detected, running frontend tests..."

            # Change to the frontend directory
            cd ui/react_frontend

            # Install dependencies with pnpm
            Write-Host "Installing dependencies with pnpm..."
            pnpm install

            # Run the CI-friendly tests
            Write-Host "Running CI-friendly tests..."
            $env:CI = "true"
            $env:PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

            # First ensure the report directory exists
            node tests/ensure_report_dir.js

            # Run the simple test that doesn't require browser installation
            pnpm test:ci:windows || Write-Host "Frontend tests completed with non-zero exit code, but continuing..."

            # Return to the original directory
            cd ../..
          } else {
            Write-Host "No React frontend detected, skipping frontend tests."
          }
        continue-on-error: true

      - name: Upload frontend test reports
        if: runner.os == 'Windows' && hashFiles('ui/react_frontend/playwright-report/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-reports-${{ runner.os }}-${{ github.run_id }}
          path: ui/react_frontend/playwright-report/
          if-no-files-found: warn
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  security:
    name: Security Scan
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache uv dependencies (Security)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.uv
          key: ${{ runner.os }}-uv-security-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-security-

      - name: Install uv (Unix)
        if: runner.os != 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install uv (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install uv
        shell: pwsh

      - name: Install security tools (Unix)
        if: runner.os != 'Windows'
        run: |
          # Create a virtual environment using 'uv'
          # 'uv' is used here instead of the standard 'venv' module because it provides faster environment creation and dependency resolution
          # Ensure 'uv' is installed and available in the environment
          if ! command -v uv &> /dev/null; then
            echo "'uv' is not installed or not in PATH. Please ensure it is installed before running this workflow." >&2
            exit 1
          fi
          uv venv .venv
          source .venv/bin/activate
          uv pip install safety bandit semgrep pip-audit gitleaks-scan

          # Create directory for security reports
          mkdir -p security-reports

          # Generate Bandit configuration based on platform
          cat > .github/bandit/bandit-config-$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')-${{ github.run_id }}.yaml << 'EOF'
          exclude_dirs: ['.venv', 'node_modules', 'tests']
          skips: ['B101', 'B104']
          EOF

      - name: Install security tools (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Create a virtual environment using 'uv'
          # 'uv' is used here instead of the standard 'venv' module because it provides faster environment creation and dependency resolution
          # Ensure 'uv' is installed and available in the environment
          if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
            Write-Error "'uv' is not installed or not in PATH. Please ensure it is installed before running this workflow."
            exit 1
          }
          uv venv .venv
          .\.venv\Scripts\Activate.ps1
          uv pip install safety bandit semgrep pip-audit gitleaks-scan

          # Create directory for security reports
          New-Item -ItemType Directory -Force -Path security-reports

          # Generate Bandit configuration based on platform
          $banditConfig = @"
          exclude_dirs: ['.venv', 'node_modules', 'tests']
          skips: ['B101', 'B104']
          "@
          New-Item -ItemType Directory -Force -Path .github/bandit
          Set-Content -Path ".github/bandit/bandit-config-$(('${{ runner.os }}').ToLower())-${{ github.run_id }}.yaml" -Value $banditConfig

      - name: Run security scans (Unix)
        if: runner.os != 'Windows'
        run: |
          # Run safety check
          safety check --full-report || true

          # Run Bandit with the generated configuration
          platform=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')
          bandit_config_file=".github/bandit/bandit-config-${platform}-${{ github.run_id }}.yaml"
          if [ -f "$bandit_config_file" ]; then
            echo "Using Bandit configuration file: $bandit_config_file"
            bandit -r . -f sarif -o security-reports/bandit-results.sarif -c "$bandit_config_file" --exclude ".venv,node_modules,tests" || true
          else
            echo "Bandit configuration file not found. Using default configuration."
            bandit -r . -f sarif -o security-reports/bandit-results.sarif --exclude ".venv,node_modules,tests" || true
          fi

          # Ensure the SARIF file exists
          if [ ! -f "security-reports/bandit-results.sarif" ]; then
            echo "Bandit did not generate a SARIF file. Creating an empty one."
            cat > security-reports/bandit-results.sarif << 'EOF'
            {
              "version": "2.1.0",
              "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
              "runs": [
                {
                  "tool": {
                    "driver": {
                      "name": "Bandit",
                      "informationUri": "https://github.com/PyCQA/bandit",
                      "version": "1.7.5",
                      "rules": []
                    }
                  },
                  "results": []
                }
              ]
            }
            EOF
          fi

          # Run pip-audit
          pip-audit || true

          # Run semgrep
          semgrep scan --config auto || true

          # Run gitleaks
          gitleaks detect --report-path=security-reports/gitleaks-report.json || true

      - name: Run security scans (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Run safety check
          safety check --full-report

          # Run Bandit with the generated configuration
          $platform = ('${{ runner.os }}').ToLower()
          $banditConfigFile = ".github/bandit/bandit-config-${platform}-${{ github.run_id }}.yaml"
          if (Test-Path $banditConfigFile) {
            Write-Host "Using Bandit configuration file: $banditConfigFile"
            bandit -r . -f sarif -o security-reports/bandit-results.sarif -c $banditConfigFile --exclude ".venv,node_modules,tests"
          } else {
            Write-Host "Bandit configuration file not found. Using default configuration."
            bandit -r . -f sarif -o security-reports/bandit-results.sarif --exclude ".venv,node_modules,tests"
          }

          # Ensure the SARIF file exists
          if (-not (Test-Path "security-reports/bandit-results.sarif")) {
            Write-Host "Bandit did not generate a SARIF file. Creating an empty one."
            $emptySarif = @"
            {
              "version": "2.1.0",
              "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
              "runs": [
                {
                  "tool": {
                    "driver": {
                      "name": "Bandit",
                      "informationUri": "https://github.com/PyCQA/bandit",
                      "version": "1.7.5",
                      "rules": []
                    }
                  },
                  "results": []
                }
              ]
            }
            "@
            Set-Content -Path "security-reports/bandit-results.sarif" -Value $emptySarif
          }

          # Run pip-audit
          pip-audit

          # Run semgrep
          semgrep scan --config auto

          # Run gitleaks
          gitleaks detect --report-path=security-reports/gitleaks-report.json
        continue-on-error: true

      - name: Upload Bandit SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: security-reports/bandit-results.sarif
          category: bandit-${{ runner.os }}
        continue-on-error: true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ runner.os }}-${{ github.run_id }}
          path: security-reports/
          if-no-files-found: warn
          retention-days: 7

  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: [lint-test, security]
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')) ||
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      docker_tag: ${{ steps.set-docker-tag.outputs.docker_tag }}
      should_push: ${{ steps.set-docker-tag.outputs.should_push }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker image tag
        id: set-docker-tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "docker_tag=${{ secrets.DOCKERHUB_USERNAME }}/paissiveincome-app:${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "should_push=true" >> $GITHUB_OUTPUT
          else
            echo "docker_tag=paissiveincome/app:test" >> $GITHUB_OUTPUT
            echo "should_push=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,amd64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          driver-opts: |
            image=moby/buildkit:v0.12.0

      - name: Login to DockerHub
        if: steps.set-docker-tag.outputs.should_push == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare build cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ steps.set-docker-tag.outputs.should_push }}
          tags: ${{ steps.set-docker-tag.outputs.docker_tag }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          provenance: mode=max

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache