name: Consolidated CI/CD

on:
  push:
    branches: [ main, dev, master, develop ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main, dev, master, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly, for regular security scans
  workflow_dispatch:

permissions:
  # Default: no broad permissions for all jobs, override per job/step
  contents: read

jobs:
  lint-test:
    name: Lint, Type Check, and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      # Use more restrictive permissions here if possible
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff flake8 black isort mypy pytest pytest-cov pytest-xdist pytest-asyncio
          pip install -r requirements-dev.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e . -v

      - name: Lint with Ruff/Flake8/Black/Isort
        run: |
          ruff check .
          ruff format --check .
          flake8 .
          black --check .
          isort --check-only .

      - name: Type check with mypy
        run: mypy .

      - name: Run tests (pytest, junit, coverage)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p junit
          pytest -n auto -v \
            --import-mode=importlib \
            --cov=. \
            --cov-report=xml \
            --cov-report=term-missing \
            --junitxml=junit/test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: junit/test-results.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

  security:
    name: Security & SAST
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit pip-audit semgrep pylint sarif-tools
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Safety
        continue-on-error: true
        run: |
          mkdir -p security-reports
          safety check --json > security-reports/safety-results.json || echo "[]"

      - name: Run pip-audit
        continue-on-error: true
        run: |
          pip-audit --format json > security-reports/pip-audit-results.json || echo "[]"

      - name: Run Bandit
        continue-on-error: true
        run: |
          bandit -r . -f json -o security-reports/bandit-results.json || echo '{"results": []}'
          # Convert Bandit JSON to SARIF for upload to GitHub
          sarif tools convert bandit security-reports/bandit-results.json security-reports/bandit-results.sarif || echo "{\"runs\": []}" > security-reports/bandit-results.sarif

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'security-reports/trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Run Semgrep
        continue-on-error: true
        run: |
          semgrep scan --config=auto --severity=ERROR || true

      - name: Run pylint (security warnings)
        continue-on-error: true
        run: |
          pylint --disable=all --enable=security . || true

      - name: Fix potential secrets
        run: python fix_potential_secrets.py

      - name: Run secret scanning (gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          report-format: sarif
          report-path: security-reports/gitleaks-report.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: security-reports/
          retention-days: 7

      - name: Upload Bandit scan SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: security-reports/bandit-results.sarif
          category: bandit

      - name: Upload Trivy scan SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: security-reports/trivy-results.sarif
          category: trivy

      - name: Run CodeQL Init
        uses: github/codeql-action/init@v3
        with:
          languages: python, javascript-typescript
          queries: security-and-quality

      - name: Run CodeQL Analyze
        uses: github/codeql-action/analyze@v3

      - name: Dependency Review (PRs only)
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v4

  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: [lint-test, security]
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')) ||
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
      id-token: write  # Needed for OIDC auth to cloud providers
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ startsWith(github.ref, 'refs/tags/v') && format('{0}/{1}:{2}', secrets.DOCKERHUB_USERNAME, 'paissiveincome-app', github.ref_name) || 'paissiveincome/app:test' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ format('{0}/{1}:{2}', secrets.DOCKERHUB_USERNAME, 'paissiveincome-app', github.ref_name) }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # === Docker Hub Deployment Details ===
      # - Deployment occurs ONLY for tags matching v*.*.*
      # - Requires GitHub secrets:
      #     DOCKERHUB_USERNAME: your Docker Hub username
      #     DOCKERHUB_TOKEN: a Docker Hub access token (from Docker Hub > Account Settings > Security)
      # - Set these in GitHub: Settings > Secrets and variables > Actions > New repository secret

# === BRANCH PROTECTION & SECRETS BEST PRACTICES ===
# - Set up branch protection for main/dev/master (require status checks, require PR reviews, restrict who can push, etc.).
# - Store all credentials (deployment, Docker, cloud) as encrypted GitHub secrets or use OIDC with minimal permissions.
# - Review permissions: jobs default to 'contents: read', escalate only where needed (e.g. 'packages: write' for Docker, 'id-token: write' for OIDC/cloud).
# - Make sure all workflow and test/lint scripts respect .gitignore (exclude venv, build, dist, etc. from scans).
# - Regularly audit repository secrets and permissions.