name: Post-Merge Tests (and Deploy Placeholder)

on:
  push:
    branches: [ main, master, develop ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  # TODO: Replace this duplicated test logic by calling a reusable test workflow (see .github/workflows/ci.yml).
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .pytest_cache
          key: ${{ runner.os }}-pip-deploy-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-deploy-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install core dependencies
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

          # Install service dependencies
          for req in $(find . -name "requirements.txt" ! -path "./requirements.txt"); do
            echo "Installing dependencies from $req"
            python -m pip install -r $req
          done

      - name: Create junit directory
        run: mkdir -p junit

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests \
            -n auto \
            --import-mode=importlib \
            --cov=. \
            --cov-report=xml \
            --cov-report=term-missing \
            --junitxml=junit/test-results.xml

  # Example placeholder for a future deployment job:
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to production
  #       run: echo "Add your deployment steps here (e.g., Docker build/push, cloud deploy, etc.)"
