name: Post-Merge Tests (and Deploy Placeholder)

on:
  push:
    branches: [ main, master, develop ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      python-version: '3.12'
      test-path: 'tests/'

  # Example placeholder for a future deployment job:
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to production
  #       run: echo "Add your deployment steps here (e.g., Docker build/push, cloud deploy, etc.)"
