name: Docker Compose Integration

on:
  pull_request:
    branches: [main, master]

jobs:
  docker-compose-integration:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up Docker Compose explicitly
      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--detach"

      # Install curl for health checks
      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Wait for Flask app to be healthy
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:5000/health; then
              echo "Flask app is healthy."
              exit 0
            else
              echo "Waiting for Flask app..."
              sleep 5
            fi
          done
          echo "Flask app did not become healthy in time."
          docker compose logs || docker-compose logs
          exit 1

      # The Docker Compose action will automatically tear down services in its post-run step
