name: Docker Compose Alternative Integration

on:
  # This is a template workflow - uncomment to enable
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:  # Allow manual triggering

jobs:
  docker-compose-integration:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Alternative approach using Docker's official GitHub Action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build and start services
        run: |
          docker-compose up --build -d

      - name: Wait for Flask app to be healthy
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:5000/health; then
              echo "Flask app is healthy."
              exit 0
            else
              echo "Waiting for Flask app..."
              sleep 5
            fi
          done
          echo "Flask app did not become healthy in time."
          docker-compose logs
          exit 1

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down -v
