name: Docker Compose Integration

on:
  push:
    branches: [ main, develop, cosine/add/ag-ui-pnpm-zt2ztr ]
    paths:
      - 'docker-compose*.yml'
      - 'scripts/fix-docker-*.sh'
      - 'scripts/run-docker-compose-ci.sh'
      - '.github/workflows/docker-compose.yml'
      - 'ui/react_frontend/Dockerfile.dev'
      - 'ui/react_frontend/package.json'
      - 'Dockerfile'
      - 'docker-healthcheck.sh'
      - 'wait-for-db.sh'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docker-compose*.yml'
      - 'scripts/fix-docker-*.sh'
      - 'scripts/run-docker-compose-ci.sh'
      - '.github/workflows/docker-compose.yml'
      - 'ui/react_frontend/Dockerfile.dev'
      - 'ui/react_frontend/package.json'
      - 'Dockerfile'
      - 'docker-healthcheck.sh'
      - 'wait-for-db.sh'
  workflow_dispatch:  # Allow manual triggering

jobs:
  docker-compose-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Initial disk space check
        run: |
          echo "Initial disk space:"
          df -h
          echo "Memory usage:"
          free -m

      - name: Clean up runner workspace
        run: |
          echo "Cleaning up runner workspace..."
          rm -rf /tmp/* || true
          sudo apt-get clean
          echo "Disk space after workspace cleanup:"
          df -h

      - name: Clean up Docker system
        run: |
          echo "Cleaning up unused Docker images, containers, and volumes..."
          docker system prune -a -f --volumes
          echo "Disk space after Docker cleanup:"
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check for frontend
        id: check-frontend
        run: |
          if [ -d "ui/react_frontend" ]; then
            echo "has_frontend=true" >> $GITHUB_OUTPUT
          else
            echo "has_frontend=false" >> $GITHUB_OUTPUT
          fi

      - name: Install pnpm
        if: steps.check-frontend.outputs.has_frontend == 'true'
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Set up Node.js
        if: steps.check-frontend.outputs.has_frontend == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Make scripts executable
        run: |
          chmod +x scripts/fix-docker-network.sh
          chmod +x scripts/fix-docker-compose.sh
          chmod +x scripts/fix-docker-compose-improved.sh
          chmod +x scripts/fix-docker-compose-errors.sh
          chmod +x scripts/run-docker-compose-ci.sh
          chmod +x docker-healthcheck.sh || true
          chmod +x wait-for-db.sh || true

      - name: Fix Docker network
        run: |
          echo "Running Docker network fix script..."
          ./scripts/fix-docker-network.sh

      - name: Fix Docker Compose
        run: |
          echo "Running Docker Compose fix script..."
          chmod +x scripts/fix-docker-compose-improved.sh
          chmod +x scripts/fix-docker-compose-errors.sh
          ./scripts/fix-docker-compose-improved.sh

          # Run the enhanced error handling script
          echo "Running enhanced Docker Compose error handling script..."
          ./scripts/fix-docker-compose-errors.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: |
            image=moby/buildkit:v0.12.0
          buildkitd-flags: --debug

      # Debug Docker networks
      - name: Debug Docker networks
        run: |
          echo "Inspecting all Docker networks..."
          docker network ls
          echo "Inspecting 'paissive-network'..."
          docker network inspect paissive-network || echo "Network 'paissive-network' does not exist."

      # Check if Docker Hub secrets are set
      - name: Check Docker Hub secrets
        id: check-secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "::warning::DOCKERHUB_USERNAME and/or DOCKERHUB_TOKEN secrets are not set. Docker Hub login will be skipped, which may lead to rate limiting."
            echo "dockerhub_secrets_set=false" >> $GITHUB_OUTPUT
          else
            echo "dockerhub_secrets_set=true" >> $GITHUB_OUTPUT
          fi

      # Log in to Docker Hub to avoid rate limits
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: steps.check-secrets.outputs.dockerhub_secrets_set == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Check disk space before pulling images
      - name: Check disk space before pulling images
        run: |
          echo "Disk space before pulling images:"
          df -h

      # Build and start services with Docker Compose
      - name: Build and start services
        run: |
          # Run the Docker Compose CI script
          echo "Running Docker Compose CI script..."
          ./scripts/run-docker-compose-ci.sh

      # Check Docker services status
      - name: Check Docker services status
        run: |
          echo "Checking Docker services status..."

          # Function to check if a command exists
          command_exists() {
            command -v "$1" >/dev/null 2>&1
          }

          # Determine which Docker Compose command to use
          if command_exists "docker compose"; then
            COMPOSE_CMD="docker compose"
          elif command_exists "docker-compose"; then
            COMPOSE_CMD="docker-compose"
          else
            echo "WARNING: No Docker Compose installation found. Using 'docker compose' anyway."
            COMPOSE_CMD="docker compose"
          fi

          # Set CI-specific variables
          export CI=true
          export GITHUB_ACTIONS=true
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1

          $COMPOSE_CMD ps || echo "WARNING: Could not get Docker Compose status, but continuing anyway."
          echo "Docker disk usage:"
          docker system df || echo "WARNING: Could not get Docker system disk usage, but continuing anyway."

          # Check container logs for debugging
          echo "Container logs:"
          docker logs paissive-income-app 2>&1 || echo "WARNING: Could not get app container logs, but continuing anyway."
          docker logs paissive-postgres 2>&1 || echo "WARNING: Could not get database container logs, but continuing anyway."
          if [ -d "ui/react_frontend" ]; then
            docker logs paissive-frontend 2>&1 || echo "WARNING: Could not get frontend container logs, but continuing anyway."
          fi

      # Run tests if available
      - name: Run tests
        run: |
          echo "Running tests..."

          # Function to check if a command exists
          command_exists() {
            command -v "$1" >/dev/null 2>&1
          }

          # Determine which Docker Compose command to use
          if command_exists "docker compose"; then
            COMPOSE_CMD="docker compose"
          elif command_exists "docker-compose"; then
            COMPOSE_CMD="docker-compose"
          else
            echo "WARNING: No Docker Compose installation found. Using 'docker compose' anyway."
            COMPOSE_CMD="docker compose"
          fi

          # Set CI-specific variables
          export CI=true
          export GITHUB_ACTIONS=true
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1

          # Run backend tests if available
          echo "Running backend tests..."
          $COMPOSE_CMD exec -T app python -m pytest || echo "WARNING: Backend tests failed or not available, but continuing anyway."

          # Run frontend tests if available
          if [ -d "ui/react_frontend" ]; then
            echo "Running frontend tests..."
            # Use CI mode for frontend tests
            $COMPOSE_CMD exec -T frontend sh -c "CI=true npm test -- --watchAll=false" || echo "WARNING: Frontend tests failed or not available, but continuing anyway."
          else
            echo "No frontend directory found, skipping frontend tests."
          fi

      # Tear down Docker Compose
      - name: Tear down Docker Compose
        if: always()
        run: |
          echo "Tearing down Docker Compose..."

          # Function to check if a command exists
          command_exists() {
            command -v "$1" >/dev/null 2>&1
          }

          # Determine which Docker Compose command to use
          if command_exists "docker compose"; then
            COMPOSE_CMD="docker compose"
          elif command_exists "docker-compose"; then
            COMPOSE_CMD="docker-compose"
          else
            echo "WARNING: No Docker Compose installation found. Using 'docker compose' anyway."
            COMPOSE_CMD="docker compose"
          fi

          # Set CI-specific variables
          export CI=true
          export GITHUB_ACTIONS=true
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1

          # Save logs before tearing down
          echo "Saving container logs before teardown..."
          mkdir -p ./logs
          docker logs paissive-income-app > ./logs/app.log 2>&1 || echo "WARNING: Could not save app logs"
          docker logs paissive-postgres > ./logs/db.log 2>&1 || echo "WARNING: Could not save db logs"
          if [ -d "ui/react_frontend" ]; then
            docker logs paissive-frontend > ./logs/frontend.log 2>&1 || echo "WARNING: Could not save frontend logs"
          fi

          # Try to tear down with Docker Compose
          echo "Running Docker Compose down command..."
          $COMPOSE_CMD down -v || {
            echo "WARNING: Docker Compose down failed. Trying alternative cleanup..."
            # Try to stop and remove containers directly
            docker stop $(docker ps -a -q) 2>/dev/null || true
            docker rm -f $(docker ps -a -q) 2>/dev/null || true
            docker network rm paissive-network 2>/dev/null || true
          }

          # Clean up volumes
          echo "Cleaning up Docker volumes..."
          docker volume prune -f || echo "WARNING: Could not prune volumes"

          # Always exit with success to allow the workflow to continue
          exit 0

      # Final system status
      - name: Final system status
        if: always()
        run: |
          echo "Final system status:"

          # Function to check if a command exists
          command_exists() {
            command -v "$1" >/dev/null 2>&1
          }

          # Determine which Docker Compose command to use
          if command_exists "docker compose"; then
            COMPOSE_CMD="docker compose"
          elif command_exists "docker-compose"; then
            COMPOSE_CMD="docker-compose"
          else
            echo "WARNING: No Docker Compose installation found. Using 'docker compose' anyway."
            COMPOSE_CMD="docker compose"
          fi

          # Set CI-specific variables
          export CI=true
          export GITHUB_ACTIONS=true
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1

          echo "Docker Compose version:"
          $COMPOSE_CMD version || echo "WARNING: Could not get Docker Compose version"

          echo "Docker system info:"
          docker info || echo "WARNING: Could not get Docker system info"

          echo "Docker disk usage:"
          docker system df -v || echo "WARNING: Could not get Docker disk usage"

          echo "Docker service status:"
          $COMPOSE_CMD ps || docker ps || echo "WARNING: Could not get Docker service status"

          echo "Docker images:"
          docker images || echo "WARNING: Could not get Docker images"

          echo "Docker containers (all):"
          docker ps -a || echo "WARNING: Could not get Docker containers"

          echo "Final disk space:"
          df -h || echo "WARNING: Could not get disk space"

          echo "Memory usage:"
          free -m || echo "WARNING: Could not get memory usage"

          # Upload logs as artifacts if they exist
          if [ -d "./logs" ]; then
            echo "Container logs are available in the logs directory"
            ls -la ./logs || echo "WARNING: Could not list logs directory"
          fi

      # Upload logs as artifacts
      - name: Upload logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-logs
          path: |
            ./logs/
          retention-days: 5
