name: Docker Compose Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Docker Compose V2
      run: |
        # Install Docker Compose v2 using the standard Docker package installation
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
        docker compose version # Verify installation
        
    - name: Build and start services
      run: |
        # Try to start services
        echo "Starting services with docker compose..."
        docker compose up -d
        
        # Check if services started
        echo "Checking if services started..."
        if ! docker compose ps; then
          echo "ERROR: Failed to start services with docker compose. Trying with build flag..."
          docker compose up -d --build
        fi
        
        # Final check
        echo "Final service status check:"
        docker compose ps
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1

    - name: Run tests
      run: |
        # Add your test commands here
        echo "Running integration tests..."
        # Example: pytest tests/integration/
