name: Docker Compose Local Test

on:
  pull_request:
    branches: [main, master]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Docker network
        run: |
          docker network create paissive-network || echo "Network already exists"
          docker network ls
      
      - name: Set up Docker Compose
        run: |
          docker compose version || docker-compose version
          docker compose config || docker-compose config
      
      - name: Start services
        run: |
          docker compose up -d
          docker compose ps
      
      - name: Check service health
        run: |
          docker compose ps
          docker ps
          echo "Waiting for services to be healthy..."
          sleep 30
          docker compose logs
