name: Fix All Issues (Windows)

on:
  workflow_dispatch:
    inputs:
      specific_file:
        description: 'Specific file to fix'
        required: false
        type: string
      syntax_only:
        description: 'Fix only syntax errors'
        required: false
        default: false
        type: boolean
      format_only:
        description: 'Fix only formatting issues'
        required: false
        default: false
        type: boolean
      no_black:
        description: 'Skip Black formatter'
        required: false
        default: false
        type: boolean
      no_isort:
        description: 'Skip isort'
        required: false
        default: false
        type: boolean
      no_ruff:
        description: 'Skip Ruff linter'
        required: false
        default: false
        type: boolean
      verbose:
        description: 'Enable verbose output'
        required: false
        default: true
        type: boolean

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-fix-issues.yml
    with:
      specific_file: ${{ inputs.specific_file }}
      syntax_only: ${{ inputs.syntax_only }}
      format_only: ${{ inputs.format_only }}
      no_black: ${{ inputs.no_black }}
      no_isort: ${{ inputs.no_isort }}
      no_ruff: ${{ inputs.no_ruff }}
      verbose: ${{ inputs.verbose }}
      shell: 'pwsh'
