name: Fix Syntax Issues

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
  push:
    branches:
      - main
      - fix_ci_workflow
    paths:
      - '**.py'

jobs:
  fix-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit check
        id: pre-commit
        continue-on-error: true
        run: |
          pre-commit run check-ast --all-files

      - name: Fix syntax issues if pre-commit failed
        if: steps.pre-commit.outcome == 'failure'
        run: |
          python fix_all_files.py

      - name: Run pre-commit check again
        id: pre-commit-again
        continue-on-error: true
        run: |
          pre-commit run check-ast --all-files

      - name: Commit changes
        if: steps.pre-commit.outcome == 'failure' && steps.pre-commit-again.outcome == 'success'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Fix syntax issues automatically" || echo "No changes to commit"
          git push
