name: Frontend Unit Tests (Vitest)

on:
  pull_request:
    paths:
      - "ui/react_frontend/**"
      - ".github/workflows/frontend-vitest.yml"

jobs:
  vitest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/react_frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Vitest unit tests
        run: pnpm run test:unit

      - name: Upload Vitest coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-coverage-report-${{ github.run_id }}
          path: ui/react_frontend/coverage