name: Frontend E2E Tests

on:
  push:
    paths:
      - "ui/react_frontend/**"
      - ".github/workflows/frontend-e2e.yml"
  pull_request:
    paths:
      - "ui/react_frontend/**"
      - ".github/workflows/frontend-e2e.yml"

jobs:
  e2e:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui/react_frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start backend API server
        run: |
          pip install -r ../../requirements.txt
          pip install -r ../../requirements-dev.txt
          pip install -e ../..
          nohup python ../../ui/api_server.py &

      - name: Start React development server
        run: |
          nohup npm start -- --port=3000 &
          sleep 10

      - name: Run Playwright E2E tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ui/react_frontend/playwright-report/
