name: Frontend E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        if ! which pnpm; then
          echo "pnpm not found, installing globally with npm..."
          npm install -g pnpm
        fi
        pnpm install --no-optional || npm install --no-optional

    - name: Create test directories
      run: |
        mkdir -p tests/e2e
        mkdir -p tests/__mocks__
        mkdir -p ci-reports ci-artifacts ci-logs ci-temp ci-cache

    - name: Set up CI environment
      run: |
        echo "CI=true" >> $GITHUB_ENV
        echo "CI_ENVIRONMENT=true" >> $GITHUB_ENV
        echo "CI_TYPE=github" >> $GITHUB_ENV
        echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV
        echo "CI_PLATFORM=github" >> $GITHUB_ENV
        echo "CI_OS=$(uname -s)" >> $GITHUB_ENV
        echo "CI_ARCH=$(uname -m)" >> $GITHUB_ENV
        echo "CI_NODE_VERSION=$(node --version)" >> $GITHUB_ENV
        echo "CI_RUNNER_OS=${{ runner.os }}" >> $GITHUB_ENV
        echo "CI_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run E2E tests
      env:
        NODE_ENV: test
        CI: true
        REACT_APP_API_BASE_URL: http://localhost:3001
        E2E_TIMEOUT: 30000
      run: |
        pnpm run test:e2e -- --coverage || npm run test:e2e -- --coverage

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        fail_ci_if_error: true
