name: Frontend Unit Tests (Vitest)

on:
  pull_request:
    paths:
      - "ui/react_frontend/**"
      - ".github/workflows/frontend-vitest.yml"

jobs:
  vitest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/react_frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Add pnpm to PATH
        shell: bash
        run: |
          export PATH=$(pnpm bin):$PATH
          echo "PATH=$(pnpm bin):$PATH" >> $GITHUB_ENV

      - name: Verify pnpm in PATH
        shell: bash
        run: |
          echo "Current PATH: $PATH"
          which pnpm || { echo "Error: pnpm is still not in PATH."; exit 1; }

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Check pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Create test directory if it doesn't exist
        run: |
          mkdir -p src/__tests__
          if [ ! -f "src/__tests__/dummy.test.ts" ] && [ ! -f "tests/dummy.test.ts" ] && [ ! -f "src/__tests__/dummy.test.tsx" ] && [ ! -f "tests/dummy.test.tsx" ]; then
            echo "// Dummy test file to ensure coverage directory is created
            import { describe, it, expect } from 'vitest';

            describe('Dummy test', () => {
              it('should pass', () => {
                expect(true).toBe(true);
              });
            });" > src/__tests__/dummy.test.ts
            echo "Created dummy test file to ensure coverage directory is created"
          else
            echo "Test files already exist, skipping dummy test creation"
          fi

      - name: Run Vitest unit tests
        run: pnpm run test:unit

      - name: Upload Vitest coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-coverage-report-${{ github.run_id }}
          path: ui/react_frontend/coverage