name: MCP Adapter Tests

on:
  push:
    branches: [ main, dev, master, develop ]
    paths:
      - 'ai_models/adapters/mcp_adapter.py'
      - 'ai_models/adapters/adapter_factory.py'
      - 'ai_models/adapters/exceptions.py'
      - 'tests/ai_models/adapters/test_mcp_adapter.py'
      - 'tests/test_mcp_import.py'
      - 'tests/test_mcp_top_level_import.py'
      - 'tests/ai_models/adapters/conftest.py'
      - 'tests/ai_models/adapters/pytest.ini'
      - 'run_mcp_tests.py'
      - 'install_mcp_sdk.py'
      - 'scripts/run/run_mcp_tests.py'
      - 'scripts/setup/install_mcp_sdk.py'
      - '.github/workflows/mcp-adapter-tests.yml'
  pull_request:
    branches: [ main, dev, master, develop ]
    paths:
      - 'ai_models/adapters/mcp_adapter.py'
      - 'ai_models/adapters/adapter_factory.py'
      - 'ai_models/adapters/exceptions.py'
      - 'tests/ai_models/adapters/test_mcp_adapter.py'
      - 'tests/test_mcp_import.py'
      - 'tests/test_mcp_top_level_import.py'
      - 'tests/ai_models/adapters/conftest.py'
      - 'tests/ai_models/adapters/pytest.ini'
      - 'run_mcp_tests.py'
      - 'install_mcp_sdk.py'
      - 'scripts/run/run_mcp_tests.py'
      - 'scripts/setup/install_mcp_sdk.py'
      - '.github/workflows/mcp-adapter-tests.yml'

jobs:
  test-mcp-adapter:
    name: Test MCP Adapter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (Unix)
        if: runner.os != 'Windows'
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-xdist pytest-asyncio

          # Check if requirements.txt exists
          if [ -f "requirements.txt" ] || [ -e "requirements.txt" ]; then
            echo "Installing dependencies from requirements.txt"
            python -m pip install -r requirements.txt || {
              echo "Failed to install dependencies from requirements.txt"
              echo "Installing minimal dependencies for MCP tests"
              python -m pip install pyyaml requests
            }
          else
            echo "requirements.txt not found, installing minimal dependencies for MCP tests"
            python -m pip install pyyaml requests
          fi

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-xdist pytest-asyncio

          # Set CI environment variables
          $env:CI = "true"
          $env:GITHUB_ACTIONS = "true"

          # Check if requirements.txt exists
          if (Test-Path "requirements.txt") {
            Write-Host "Installing dependencies from requirements.txt"
            try {
              # Install minimal dependencies first to ensure basic functionality
              python -m pip install pyyaml requests

              # Then try to install from requirements.txt
              python -m pip install -r requirements.txt
            } catch {
              Write-Host "Failed to install dependencies from requirements.txt"
              Write-Host "Installing minimal dependencies for MCP tests"
              python -m pip install pyyaml requests
            }
          } else {
            Write-Host "requirements.txt not found, installing minimal dependencies for MCP tests"
            python -m pip install pyyaml requests
          }

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-xdist pytest-asyncio
          python -m pip install -r requirements.txt
          python -m pip install email-validator
          # Install Python version-specific dependencies
          if (Test-Path requirements-py311.txt) {
            python -m pip install -r requirements-py311.txt
          }

      - name: Install MCP SDK (Unix)
        if: runner.os != 'Windows'
        run: |
          # Try to install MCP SDK with retry
          python install_mcp_sdk.py || python install_mcp_sdk.py || echo "Failed to install MCP SDK, continuing anyway"
          # Create a simple mock module if needed
          if [ ! -f "$(python -c 'import sys; print(sys.prefix)')/lib/python*/site-packages/modelcontextprotocol/__init__.py" ]; then
            echo "Creating mock module directory"
            mkdir -p "$(python -c 'import sys; print(sys.prefix)')/lib/python$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')/site-packages/modelcontextprotocol"
            echo '
__version__ = "0.1.0"

class Client:
    def __init__(self, endpoint, **kwargs):
        self.endpoint = endpoint
        self.kwargs = kwargs

    def connect(self):
        pass

    def disconnect(self):
        pass

    def send_message(self, message):
        return f"Mock response to: {message}"
' > "$(python -c 'import sys; print(sys.prefix)')/lib/python$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')/site-packages/modelcontextprotocol/__init__.py"
          fi

      - name: Install MCP SDK (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Try to install MCP SDK with retry
          python install_mcp_sdk.py || python install_mcp_sdk.py || echo "Failed to install MCP SDK, continuing anyway"
          # Create a simple mock module if needed
          $sitePackages = python -c "import site; print(site.getsitepackages()[0])"
          $mockDir = Join-Path $sitePackages "modelcontextprotocol"
          if (-not (Test-Path (Join-Path $mockDir "__init__.py"))) {
            echo "Creating mock module directory"
            New-Item -ItemType Directory -Path $mockDir -Force
            @'
__version__ = "0.1.0"

class Client:
    def __init__(self, endpoint, **kwargs):
        self.endpoint = endpoint
        self.kwargs = kwargs

    def connect(self):
        pass

    def disconnect(self):
        pass

    def send_message(self, message):
        return f"Mock response to: {message}"
'@ | Out-File -FilePath (Join-Path $mockDir "__init__.py") -Encoding utf8
          }

      - name: Run MCP adapter tests (Unix)
        if: runner.os != 'Windows'
        run: |
          python run_mcp_tests.py

      - name: Run MCP adapter tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python run_mcp_tests.py

      - name: Run MCP adapter tests with coverage (Unix)
        if: runner.os != 'Windows'
        run: |
          # Use the coverage threshold of 80%
          python -m pytest -v --cov=ai_models.adapters.mcp_adapter --cov=ai_models.adapters.exceptions --cov-report=xml --cov-report=term --cov-fail-under=80 tests/ai_models/adapters/test_mcp_adapter.py tests/test_mcp_import.py tests/test_mcp_top_level_import.py --no-header --no-summary -k "not test_mcp_server" --confcutdir=tests/ai_models/adapters --noconftest

      - name: Run MCP adapter tests with coverage (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Use the coverage threshold of 80%
          python -m pytest -v --cov=ai_models.adapters.mcp_adapter --cov=ai_models.adapters.exceptions --cov-report=xml --cov-report=term --cov-fail-under=80 tests/ai_models/adapters/test_mcp_adapter.py tests/test_mcp_import.py tests/test_mcp_top_level_import.py --no-header --no-summary -k "not test_mcp_server" --confcutdir=tests/ai_models/adapters --noconftest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: mcp-adapter
          name: codecov-mcp-adapter