name: MCP Adapter Tests

on:
  push:
    branches: [ main, dev, master, develop ]
    paths:
      - 'ai_models/adapters/mcp_adapter.py'
      - 'ai_models/adapters/adapter_factory.py'
      - 'ai_models/adapters/exceptions.py'
      - 'tests/ai_models/adapters/test_mcp_adapter.py'
      - 'tests/test_mcp_import.py'
      - 'tests/test_mcp_top_level_import.py'
      - 'tests/ai_models/adapters/conftest.py'
      - 'tests/ai_models/adapters/pytest.ini'
      - 'run_mcp_tests.py'
      - 'install_mcp_sdk.py'
      - '.github/workflows/mcp-adapter-tests.yml'
  pull_request:
    branches: [ main, dev, master, develop ]
    paths:
      - 'ai_models/adapters/mcp_adapter.py'
      - 'ai_models/adapters/adapter_factory.py'
      - 'ai_models/adapters/exceptions.py'
      - 'tests/ai_models/adapters/test_mcp_adapter.py'
      - 'tests/test_mcp_import.py'
      - 'tests/test_mcp_top_level_import.py'
      - 'tests/ai_models/adapters/conftest.py'
      - 'tests/ai_models/adapters/pytest.ini'
      - 'run_mcp_tests.py'
      - 'install_mcp_sdk.py'
      - '.github/workflows/mcp-adapter-tests.yml'

jobs:
  test-mcp-adapter:
    name: Test MCP Adapter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-xdist pytest-asyncio
          python -m pip install -r requirements.txt
          python -m pip install email-validator
          # Install Python version-specific dependencies
          if [ -f requirements-py311.txt ]; then
            python -m pip install -r requirements-py311.txt
          fi

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-xdist pytest-asyncio
          python -m pip install -r requirements.txt
          python -m pip install email-validator
          # Install Python version-specific dependencies
          if (Test-Path requirements-py311.txt) {
            python -m pip install -r requirements-py311.txt
          }

      - name: Install MCP SDK (Unix)
        if: runner.os != 'Windows'
        run: |
          # Try to install MCP SDK with retry
          python install_mcp_sdk.py || python install_mcp_sdk.py || echo "Failed to install MCP SDK, continuing anyway"

      - name: Install MCP SDK (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Try to install MCP SDK with retry
          python install_mcp_sdk.py || python install_mcp_sdk.py || echo "Failed to install MCP SDK, continuing anyway"

      - name: Run MCP adapter tests (Unix)
        if: runner.os != 'Windows'
        run: |
          python run_mcp_tests.py

      - name: Run MCP adapter tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python run_mcp_tests.py

      - name: Run MCP adapter tests with coverage (Unix)
        if: runner.os != 'Windows'
        run: |
          python -m pytest -v --cov=ai_models.adapters.mcp_adapter --cov=ai_models.adapters.exceptions --cov-report=xml --cov-report=term tests/ai_models/adapters/test_mcp_adapter.py tests/test_mcp_import.py tests/test_mcp_top_level_import.py --no-header --no-summary -k "not test_mcp_server" --confcutdir=tests/ai_models/adapters --noconftest --cov-fail-under=80

      - name: Run MCP adapter tests with coverage (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m pytest -v --cov=ai_models.adapters.mcp_adapter --cov=ai_models.adapters.exceptions --cov-report=xml --cov-report=term tests/ai_models/adapters/test_mcp_adapter.py tests/test_mcp_import.py tests/test_mcp_top_level_import.py --no-header --no-summary -k "not test_mcp_server" --confcutdir=tests/ai_models/adapters --noconftest --cov-fail-under=80

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: mcp-adapter
          name: codecov-mcp-adapter
