name: Reusable Fix Issues Action

on:
  workflow_call:
    inputs:
      specific_file:
        description: 'Specific file to fix'
        required: false
        type: string
      syntax_only:
        description: 'Fix only syntax errors'
        required: false
        default: false
        type: boolean
      format_only:
        description: 'Fix only formatting issues'
        required: false
        default: false
        type: boolean
      no_black:
        description: 'Skip Black formatter'
        required: false
        default: false
        type: boolean
      no_isort:
        description: 'Skip isort'
        required: false
        default: false
        type: boolean
      no_ruff:
        description: 'Skip Ruff linter'
        required: false
        default: false
        type: boolean
      verbose:
        description: 'Enable verbose output'
        required: false
        default: false
        type: boolean
      shell:
        description: 'Shell to use (bash or pwsh)'
        required: false
        default: 'bash'
        type: string

jobs:
  fix-issues:
    runs-on: ${{ inputs.shell == 'pwsh' && 'windows-latest' || 'ubuntu-latest' }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      if: inputs.shell == 'bash'
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 black isort ruff
        python -m pip install -r requirements-dev.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install dependencies (Windows)
      if: inputs.shell == 'pwsh'
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 black isort ruff
        python -m pip install -r requirements-dev.txt
        if (Test-Path -Path "requirements.txt") {
          python -m pip install -r requirements.txt
        }
      shell: pwsh

    - name: Check script exists
      if: inputs.shell == 'bash'
      run: |
        if [ ! -f "fix_all_issues_final.py" ]; then
          echo "Error: fix_all_issues_final.py not found!"
          exit 1
        fi
        echo "Script found, proceeding..."

    - name: Check script exists (Windows)
      if: inputs.shell == 'pwsh'
      run: |
        if (-not (Test-Path -Path "fix_all_issues_final.py")) {
          Write-Error "Error: fix_all_issues_final.py not found!"
          exit 1
        }
        Write-Host "Script found, proceeding..."
      shell: pwsh

    - name: Fix issues
      if: inputs.shell == 'bash'
      run: |
        # Build command with appropriate flags
        CMD="python fix_all_issues_final.py"

        if [[ "${{ inputs.verbose }}" == "true" ]]; then
          CMD+=" --verbose"
        fi

        if [[ "${{ inputs.syntax_only }}" == "true" ]]; then
          CMD+=" --syntax-only"
        fi

        if [[ "${{ inputs.format_only }}" == "true" ]]; then
          CMD+=" --format-only"
        fi

        if [[ "${{ inputs.no_black }}" == "true" ]]; then
          CMD+=" --no-black"
        fi

        if [[ "${{ inputs.no_isort }}" == "true" ]]; then
          CMD+=" --no-isort"
        fi

        if [[ "${{ inputs.no_ruff }}" == "true" ]]; then
          CMD+=" --no-ruff"
        fi

        # Run the command with specific file or all files
        if [[ -n "${{ inputs.specific_file }}" ]]; then
          FILE_PATH="${{ inputs.specific_file }}"
          if [[ -f "$FILE_PATH" ]]; then
            echo "Fixing specific file: $FILE_PATH"
            $CMD "$FILE_PATH"
          else
            echo "Error: File $FILE_PATH not found!"
            exit 1
          fi
        else
          echo "Fixing all Python files..."
          $CMD
        fi

        # Check exit code
        if [[ $? -ne 0 ]]; then
          echo "Error: fix_all_issues_final.py failed!"
          exit 1
        fi

    - name: Fix issues (Windows)
      if: inputs.shell == 'pwsh'
      run: |
        # Build command with appropriate flags
        $CMD = "python fix_all_issues_final.py"

        if ('${{ inputs.verbose }}' -eq 'true') {
          $CMD += " --verbose"
        }

        if ('${{ inputs.syntax_only }}' -eq 'true') {
          $CMD += " --syntax-only"
        }

        if ('${{ inputs.format_only }}' -eq 'true') {
          $CMD += " --format-only"
        }

        if ('${{ inputs.no_black }}' -eq 'true') {
          $CMD += " --no-black"
        }

        if ('${{ inputs.no_isort }}' -eq 'true') {
          $CMD += " --no-isort"
        }

        if ('${{ inputs.no_ruff }}' -eq 'true') {
          $CMD += " --no-ruff"
        }

        # Run the command with specific file or all files
        if ('${{ inputs.specific_file }}' -ne '') {
          $FILE_PATH = '${{ inputs.specific_file }}'
          if (Test-Path -Path $FILE_PATH) {
            Write-Host "Fixing specific file: $FILE_PATH"
            Invoke-Expression "$CMD $FILE_PATH"
          } else {
            Write-Error "Error: File $FILE_PATH not found!"
            exit 1
          }
        } else {
          Write-Host "Fixing all Python files..."
          Invoke-Expression $CMD
        }

        # Check exit code
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Error: fix_all_issues_final.py failed!"
          exit 1
        }
      shell: pwsh

    - name: Check for changes
      id: git-check
      if: inputs.shell == 'bash'
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git status --porcelain
        else
          echo "No changes detected"
        fi

    - name: Check for changes (Windows)
      id: git-check-windows
      if: inputs.shell == 'pwsh'
      run: |
        $changes = git status --porcelain
        if ($changes) {
          Write-Host "changes=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "Changes detected:"
          Write-Host $changes
        } else {
          Write-Host "No changes detected"
        }
      shell: pwsh

    - name: Commit changes
      if: (steps.git-check.outputs.changes == 'true' || steps.git-check-windows.outputs.changes == 'true')
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .

        # Determine commit message based on what was fixed
        if [[ "${{ inputs.syntax_only }}" == "true" ]]; then
          COMMIT_MSG="Auto-fix syntax issues"
        elif [[ "${{ inputs.format_only }}" == "true" ]]; then
          COMMIT_MSG="Auto-fix formatting issues"
        else
          COMMIT_MSG="Auto-fix syntax and formatting issues"
        fi

        git commit -m "$COMMIT_MSG"
        git push
