name: Run Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']  # Focusing on Python 3.12 first

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov pytest-xdist
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
        python -m pip install -e .
    
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -m pytest tests/ai_models/test_model_info.py -v --import-mode=importlib
