name: Security Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-security-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-security-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install safety bandit pip-audit semgrep pylint sarif-tools

        # Create security-reports directory early
        mkdir -p security-reports
        echo "Created security-reports directory"

    - name: Verify sarif-tools installation
      id: sarif_tools_check
      timeout-minutes: 10
      run: |
        echo "Verifying sarif-tools installation..."
        mkdir -p security-reports

        echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"Bandit","informationUri":"https://bandit.readthedocs.io/","rules":[]}},"results":[]}]}' > security-reports/bandit-results.sarif

        echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"Trivy","informationUri":"https://github.com/aquasecurity/trivy","rules":[]}},"results":[]}]}' > security-reports/trivy-results.sarif

        # Run verification script with explicit error handling
        if ! python verify_sarif_tools.py; then
          echo "::error::Failed to verify sarif-tools installation"
          exit 1
        fi
        echo "Verification completed successfully"

    - name: Check for vulnerable dependencies with Safety
      id: safety
      timeout-minutes: 10
      continue-on-error: true
      run: |
        echo "Running Safety check..."
        mkdir -p security-reports

        if ! safety check --json > security-reports/safety-results.json 2>&1; then
          echo "::warning::Safety scan completed with issues detected"
          echo "[]" > security-reports/safety-results.json
        fi

    - name: Run bandit security scan
      id: bandit
      timeout-minutes: 10
      continue-on-error: true
      run: |
        echo "Running Bandit security scan..."
        mkdir -p security-reports

        if ! bandit -r . -f sarif -o security-reports/bandit-results.sarif; then
          echo "::warning::Bandit scan completed with security issues found"
        fi

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      timeout-minutes: 15
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'security-reports/trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Security Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: security-reports/
        retention-days: 7
        if-no-files-found: warn

    - name: Upload Bandit scan results
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      with:
        sarif_file: security-reports/bandit-results.sarif
        category: bandit

    - name: Upload Trivy scan results
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      with:
        sarif_file: security-reports/trivy-results.sarif
        category: trivy

    - name: Run dependency review
      if: github.event_name == 'pull_request'
      uses: actions/dependency-review-action@v4
