name: Python Tests (Reusable)

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      test-path:
        required: false
        type: string
        default: "tests/"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.uv
            .pytest_cache
          key: ${{ runner.os }}-uv-test-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-test-

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          # Cleanup old distributions
          find . -type d -name "*.egg-info" -exec rm -rf {} + || true
          find . -type d -name "*.dist-info" -exec rm -rf {} + || true
          find . -name "*.egg" -exec rm -f {} + || true

          # Create virtual environment with uv
          uv venv .venv || {
            echo "Failed to create virtual environment with uv. Falling back to Python's venv module..."
            python -m venv .venv
          }

          # Activate virtual environment
          source .venv/bin/activate

          # Install dependencies with uv
          uv pip install pytest pytest-cov pytest-xdist pytest-asyncio || {
            echo "Failed to install test dependencies with uv pip. Installing uv in the virtual environment..."
            python -m pip install --upgrade "uv>=0.7.8"
            uv pip install pytest pytest-cov pytest-xdist pytest-asyncio
          }

          if [ -f requirements-dev.txt ]; then
            uv pip install -r requirements-dev.txt
          fi
          if [ -f requirements.txt ]; then
            uv pip install -r requirements.txt
          fi

          uv pip install -e . -v

      - name: Create junit directory
        run: mkdir -p junit

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          # Activate virtual environment
          source .venv/bin/activate

          # Run tests with pytest
          pytest ${{ inputs.test-path }} \
            -n auto \
            -v \
            --import-mode=importlib \
            --cov=. \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=5 \
            --junitxml=junit/test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.run_id }}-${{ github.job }}
          path: junit/test-results.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_id }}
          path: coverage.xml
