name: Python Tests (Reusable)

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      test-path:
        required: false
        type: string
        default: "tests/"
      coverage-threshold:
        description: 'Coverage threshold percentage'
        required: false
        default: 15
        type: number

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.uv
            .pytest_cache
          key: ${{ runner.os }}-uv-test-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-test-

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          # Create virtual environment with uv
          uv venv .venv
          source .venv/bin/activate

          # Install test dependencies
          uv pip install pytest pytest-cov pytest-xdist pytest-asyncio

          # Install project dependencies
          if [ -f requirements.txt ]; then
            uv pip install -r requirements.txt
          fi

      - name: Create junit directory
        run: mkdir -p junit

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          # Activate virtual environment
          source .venv/bin/activate

          # Run tests with pytest
          pytest ${{ inputs.test-path }} \
            -n auto \
            -v \
            --import-mode=importlib \
            --cov=. \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=${{ inputs.coverage-threshold }} \
            --junitxml=junit/test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.run_id }}-${{ github.job }}
          path: junit/test-results.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_id }}
          path: coverage.xml
