name: Test Setup Script

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create test directories
        run: |
          mkdir -p tests/unit
          mkdir -p tests/e2e
          mkdir -p tests/mock-api
          mkdir -p tests/__mocks__
          mkdir -p ci-reports
          mkdir -p ci-artifacts
          mkdir -p ci-logs
          mkdir -p ci-temp
          mkdir -p ci-cache
          mkdir -p test-results/github
          mkdir -p logs

      - name: Set up test environment
        run: |
          echo "CI=true" >> $GITHUB_ENV
          echo "CI_ENVIRONMENT=true" >> $GITHUB_ENV
          echo "CI_TYPE=github" >> $GITHUB_ENV
          echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV
          echo "CI_PLATFORM=github" >> $GITHUB_ENV
          echo "CI_OS=$(uname -s)" >> $GITHUB_ENV
          echo "CI_ARCH=$(uname -m)" >> $GITHUB_ENV
          echo "CI_NODE_VERSION=$(node --version)" >> $GITHUB_ENV
          echo "CI_RUNNER_OS=${{ runner.os }}" >> $GITHUB_ENV
          echo "CI_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "TESTING=true" >> $GITHUB_ENV

      - name: Create dummy test files
        run: |
          # Create dummy test files if they don't exist
          touch tests/unit/dummy.test.js
          touch tests/e2e/dummy.spec.js
          touch tests/mock-api/dummy.test.js
          touch tests/__mocks__/dummy.js

      - name: Generate environment report
        run: |
          {
            echo "=== Test Environment Report ==="
            echo "Date: $(date)"
            echo "OS: $(uname -a)"
            echo "Node: $(node --version)"
            echo "npm: $(npm --version)"
            echo "Runner OS: ${{ runner.os }}"
            echo "Workspace: ${{ github.workspace }}"
            echo "Event: ${{ github.event_name }}"
            echo "Repository: ${{ github.repository }}"
            echo "Ref: ${{ github.ref }}"
            echo "SHA: ${{ github.sha }}"
            echo "=========================="
          } > ci-reports/test-environment-report.txt

      - name: Display environment report
        run: cat ci-reports/test-environment-report.txt
